services:
  sec_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IDS_USER_PASSWORD: ${IDS_USER_PASSWORD}
        CONTAINER_SSH_PORT: ${CONTAINER_SSH_PORT}
    image: secure_container_refactored
    container_name: sec_app_container
    ports:
      - "${HOST_SSH_PORT}:${CONTAINER_SSH_PORT}" # Map host port to container port
    volumes:
      - /var/log/ids_app:/var/log/ids_app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      IDS_USER_PASSWORD: ${IDS_USER_PASSWORD}
      LOG_FILE_PATH: ${LOG_FILE_PATH}
      SSH_LOG_PATH: ${SSH_LOG_PATH}
      BLACKLIST_FILE: ${BLACKLIST_FILE}
      FAILED_ATTEMPTS_THRESHOLD: ${FAILED_ATTEMPTS_THRESHOLD}
      SSHD_CONFIG_PATH: ${SSHD_CONFIG_PATH}
    privileged: true
