services:
  sec_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IDS_USER_PASSWORD: ${IDS_USER_PASSWORD} # Passing the password to the build
    image: secure_container_refactored
    container_name: sec_app_container
    ports:
      - "22222:22222" # Map host port 22222 to container port 22222
    volumes:
      - /var/log/auth.log:/host_var_log/auth.log:ro # Host logs mounted
      - /var/log/ids_app/:/var/log/ids_app/ # Container logs
      - ids_app_logs:/var/log/ids_app/
      - supervisor_logs:/var/log/supervisor/
    restart: unless-stopped
    env_file:
      - .env
    environment:
      EMAIL_ENABLED: ${EMAIL_ENABLED}
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_TO: ${EMAIL_TO}
      IDS_USER_PASSWORD: ${IDS_USER_PASSWORD}
      HOST_LOG_FILE_PATH: /host_var_log/auth.log # Log path for host
      LOG_FILE_PATH: /var/log/ids_app/ids.log # Container logs environment variable

volumes:
  ids_app_logs:
  supervisor_logs:
