services:
  sec_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IDS_USER_PASSWORD: ${IDS_USER_PASSWORD} # Passing the password to the build
    image: secure_container_refactored
    container_name: sec_app_container
    ports:
      - "${HOST_SSH_PORT}:${CONTAINER_SSH_PORT}" # Use variables from .env
    volumes:
      - /var/log/auth.log:/host_var_log/auth.log:ro # Mount host's auth.log as read-only
      - /var/log/syslog:/host_var_log/syslog:ro # Mount host's syslog (processes)
      - /var/log/ids_app:/var/log/ids_app # Container logs (for IDS app)
    restart: unless-stopped
    env_file:
      - .env # Load environment variables from the .env file
    environment:
      IDS_USER_PASSWORD: ${IDS_USER_PASSWORD}
      LOG_FILE_PATH: ${LOG_FILE_PATH}
      SSH_LOG_PATH: ${SSH_LOG_PATH}
      BLACKLIST_FILE: ${BLACKLIST_FILE}
      FAILED_ATTEMPTS_THRESHOLD: ${FAILED_ATTEMPTS_THRESHOLD}
      SSHD_CONFIG_PATH: ${SSHD_CONFIG_PATH}
    privileged: true
