# docker-compose.yml
services:
  sec_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IDS_USER_PASSWORD: ${IDS_USER_PASSWORD}
        CONTAINER_SSH_PORT: ${CONTAINER_SSH_PORT}
    image: secure_container_refactored
    container_name: sec_app_container
    ports:
      - "${HOST_SSH_PORT}:${CONTAINER_SSH_PORT}" # Maps host port to container port
    volumes:
      - ~/Documents/ids_app_data:/var/log/ids_app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      IDS_USER_PASSWORD: ${IDS_USER_PASSWORD}
      LOG_FILE_PATH: /var/log/ids_app/ids.log
      SSH_LOG_PATH: /var/log/ids_app/ids.log
      BLACKLIST_FILE: /var/log/ids_app/blacklist.txt
      FAILED_ATTEMPTS_THRESHOLD: ${FAILED_ATTEMPTS_THRESHOLD}
      SSHD_CONFIG_PATH: /etc/ssh/sshd_config
    privileged: false
    # Removed the command field to prevent overriding permissions set in Dockerfile and entrypoint.sh
    # command: |
    #   sh -c "chown -R 1001:1001 /var/log/ids_app && chmod -R 775 /var/log/ids_app && supervisord -c /etc/supervisord.conf"
    cap_add:
      - NET_ADMIN
    deploy:
      resources:
        limits:
          cpus: "0.5" # Limited to half a CPU
          memory: "512M" # Limited to 512MB of RAM
          pids: 200 # Set PID limit within deploy
        reservations:
          cpus: "0.25" # Reserves a quarter of a CPU
          memory: "256M" # Reserves 256MB of RAM
    ulimits:
      nproc: 200 # Align with pids_limit
      nofile:
        soft: 1024
        hard: 2048
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: [ "CMD-SHELL", "pgrep sshd && pgrep -f 'python3 /ids_app/ids/main.py'" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
