services:
  sec_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IDS_USER_PASSWORD: ${IDS_USER_PASSWORD}
    image: secure_container_refactored
    ports:
      - "22222:22" # Map host port 22222 to container port 22
    volumes:
      - /var/log/auth.log:/host_var_log/auth.log:ro
      - ./6130project_logs/:/var/log/ids_app/ # Ensuring logs are written to a folder
    restart: unless-stopped
    env_file:
      - .env
    environment:
      EMAIL_ENABLED: ${EMAIL_ENABLED}
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_TO: ${EMAIL_TO}
      IDS_USER_PASSWORD: ${IDS_USER_PASSWORD}
      LOG_FILE_PATH: "/var/log/ids_app/ids.log" # Use your own log file for writing logs
